# Site settings
name: Egor Kozhernovich
email: egor.kozhernovich@gmail.com
#canonical_url: https://ricpiccolo.github.io/
keywords: "Software Engineer in Test, Python, Quality assurance, Agile, Programming"
skills: "Quality Assurance Engineer in Minsk, Belarus"
baseurl:
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/yegor-kozhernovich/
  - title: facebook
    url: https://www.facebook.com/ricardo.piccolo.39
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  #under portfolio photo
  primary: b4bcc2
  #buttons
  primary-rgb: "18, 143, 118"
  #header
  secondary: 2a3135
  #header links color
  secondary-dark: 2e81b380
  # 2 section background
  section-tout: 283d723b



# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman
